apiVersion: apps/v1
kind: Deployment
metadata:
  name: wioms
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wioms
  template:
    metadata:
      labels:
        app: wioms
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: wioms
        ports:
        - containerPort: 80
