apiVersion: apps/v1
kind: Deployment
metadata:
  name: wioms
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wioms
  template:
    metadata:
      labels:
        app: wioms
    spec:
      containers:
      - image: liyubao1232000/wioms:v114
        name: wioms
        ports:
        - containerPort: 8888
